"""Initial migration

Revision ID: 8aa569eb3769
Revises: 
Create Date: 2025-12-28 23:27:41.880567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aa569eb3769'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bottles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('distillery', sa.String(length=255), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('category', sa.Enum('BOURBON', 'RYE', 'SCOTCH_SINGLE_MALT', 'SCOTCH_BLENDED', 'IRISH', 'JAPANESE', 'AMERICAN_SINGLE_MALT', 'OTHER', name='spiritcategory'), nullable=False),
    sa.Column('age_statement', sa.Integer(), nullable=True),
    sa.Column('proof', sa.Float(), nullable=True),
    sa.Column('size', sa.Enum('ML_50', 'ML_200', 'ML_375', 'ML_700', 'ML_750', 'ML_1000', 'ML_1750', 'OTHER', name='bottlesize'), nullable=False),
    sa.Column('size_ml', sa.Integer(), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('is_limited_release', sa.Boolean(), nullable=False),
    sa.Column('is_allocated', sa.Boolean(), nullable=False),
    sa.Column('msrp', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tasting_notes', sa.Text(), nullable=True),
    sa.Column('price_count', sa.Integer(), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=True),
    sa.Column('min_price', sa.Float(), nullable=True),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('last_price_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price_trend', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('stats_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bottles_brand'), 'bottles', ['brand'], unique=False)
    op.create_index(op.f('ix_bottles_category'), 'bottles', ['category'], unique=False)
    op.create_index(op.f('ix_bottles_distillery'), 'bottles', ['distillery'], unique=False)
    op.create_index(op.f('ix_bottles_id'), 'bottles', ['id'], unique=False)
    op.create_index(op.f('ix_bottles_name'), 'bottles', ['name'], unique=False)
    op.create_index(op.f('ix_bottles_normalized_name'), 'bottles', ['normalized_name'], unique=True)
    op.create_index(op.f('ix_bottles_release_year'), 'bottles', ['release_year'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'VERIFIED', 'MODERATOR', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('total_submissions', sa.Integer(), nullable=False),
    sa.Column('approved_submissions', sa.Integer(), nullable=False),
    sa.Column('rejected_submissions', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('ban_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_display_name'), 'users', ['display_name'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_display_name', sa.String(length=50), nullable=True),
    sa.Column('action', sa.Enum('USER_REGISTER', 'USER_LOGIN', 'USER_VERIFY_EMAIL', 'USER_UPDATE_PROFILE', 'USER_CHANGE_PASSWORD', 'SUBMISSION_CREATE', 'SUBMISSION_APPROVE', 'SUBMISSION_REJECT', 'SUBMISSION_AUTO_FLAG', 'MOD_APPROVE', 'MOD_REJECT', 'MOD_ADJUST_WEIGHT', 'MOD_BAN_USER', 'MOD_UNBAN_USER', 'MOD_WARN_USER', 'COLLECTION_CREATE', 'COLLECTION_ADD_ITEM', 'COLLECTION_REMOVE_ITEM', 'ADMIN_CREATE_BOTTLE', 'ADMIN_UPDATE_BOTTLE', 'ADMIN_DELETE_BOTTLE', 'ADMIN_IMPORT_DATA', 'ADMIN_UPDATE_USER_ROLE', 'SYSTEM_PRICE_IMPORT', 'SYSTEM_STATS_UPDATE', 'SYSTEM_FORECAST_RUN', name='auditaction'), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_id'), 'audit_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_type'), 'audit_logs', ['target_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('bottle_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bottle_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('normalized_alias', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bottle_id'], ['bottles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bottle_aliases_alias'), 'bottle_aliases', ['alias'], unique=False)
    op.create_index(op.f('ix_bottle_aliases_id'), 'bottle_aliases', ['id'], unique=False)
    op.create_index(op.f('ix_bottle_aliases_normalized_alias'), 'bottle_aliases', ['normalized_alias'], unique=True)
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_bottles', sa.Integer(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('value_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_id'), 'collections', ['id'], unique=False)
    op.create_index(op.f('ix_collections_user_id'), 'collections', ['user_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bottle_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_description', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'AUTO_FLAGGED', name='submissionstatus'), nullable=False),
    sa.Column('flags', sa.String(length=500), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('fraud_score', sa.Float(), nullable=False),
    sa.Column('computed_weight', sa.Float(), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bottle_id'], ['bottles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_bottle_id'), 'submissions', ['bottle_id'], unique=False)
    op.create_index(op.f('ix_submissions_id'), 'submissions', ['id'], unique=False)
    op.create_index(op.f('ix_submissions_status'), 'submissions', ['status'], unique=False)
    op.create_index(op.f('ix_submissions_user_id'), 'submissions', ['user_id'], unique=False)
    op.create_table('collection_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('bottle_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purchase_location', sa.String(length=255), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('value_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bottle_id'], ['bottles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_items_bottle_id'), 'collection_items', ['bottle_id'], unique=False)
    op.create_index(op.f('ix_collection_items_collection_id'), 'collection_items', ['collection_id'], unique=False)
    op.create_index(op.f('ix_collection_items_id'), 'collection_items', ['id'], unique=False)
    op.create_table('moderation_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('flag_type', sa.Enum('PRICE_OUTLIER', 'DUPLICATE_SUBMISSION', 'SUSPICIOUS_ACCOUNT', 'BURST_ACTIVITY', 'USER_DOMINANCE', 'MANUAL_REVIEW', 'REPORTED_BY_USER', name='moderationflag'), nullable=False),
    sa.Column('flag_reason', sa.String(length=500), nullable=False),
    sa.Column('flag_details', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_resolved', sa.Integer(), nullable=False),
    sa.Column('action_taken', sa.Enum('APPROVE', 'REJECT', 'ADJUST_WEIGHT', 'BAN_USER', 'WARN_USER', 'ESCALATE', name='moderationaction'), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderation_queue_flag_type'), 'moderation_queue', ['flag_type'], unique=False)
    op.create_index(op.f('ix_moderation_queue_id'), 'moderation_queue', ['id'], unique=False)
    op.create_index(op.f('ix_moderation_queue_is_resolved'), 'moderation_queue', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_moderation_queue_priority'), 'moderation_queue', ['priority'], unique=False)
    op.create_index(op.f('ix_moderation_queue_submission_id'), 'moderation_queue', ['submission_id'], unique=False)
    op.create_index(op.f('ix_moderation_queue_user_id'), 'moderation_queue', ['user_id'], unique=False)
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bottle_id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('price_usd', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('AUCTION', 'RETAIL', 'CROWDSOURCED', 'IMPORT', name='pricesource'), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('auction_house', sa.Enum('UNICORN', 'WHISKY_AUCTIONEER', 'SCOTCH_WHISKY_AUCTIONS', 'SOTHEBYS', 'CHRISTIES', 'OTHER', name='auctionhouse'), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_sold', sa.Boolean(), nullable=False),
    sa.Column('includes_fees', sa.Boolean(), nullable=False),
    sa.Column('confidence_weight', sa.Float(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_outlier', sa.Boolean(), nullable=False),
    sa.Column('is_excluded', sa.Boolean(), nullable=False),
    sa.Column('exclusion_reason', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bottle_id'], ['bottles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prices_bottle_id'), 'prices', ['bottle_id'], unique=False)
    op.create_index(op.f('ix_prices_id'), 'prices', ['id'], unique=False)
    op.create_index(op.f('ix_prices_price'), 'prices', ['price'], unique=False)
    op.create_index(op.f('ix_prices_price_usd'), 'prices', ['price_usd'], unique=False)
    op.create_index(op.f('ix_prices_source'), 'prices', ['source'], unique=False)
    op.create_index(op.f('ix_prices_submission_id'), 'prices', ['submission_id'], unique=False)
    op.create_index(op.f('ix_prices_transaction_date'), 'prices', ['transaction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prices_transaction_date'), table_name='prices')
    op.drop_index(op.f('ix_prices_submission_id'), table_name='prices')
    op.drop_index(op.f('ix_prices_source'), table_name='prices')
    op.drop_index(op.f('ix_prices_price_usd'), table_name='prices')
    op.drop_index(op.f('ix_prices_price'), table_name='prices')
    op.drop_index(op.f('ix_prices_id'), table_name='prices')
    op.drop_index(op.f('ix_prices_bottle_id'), table_name='prices')
    op.drop_table('prices')
    op.drop_index(op.f('ix_moderation_queue_user_id'), table_name='moderation_queue')
    op.drop_index(op.f('ix_moderation_queue_submission_id'), table_name='moderation_queue')
    op.drop_index(op.f('ix_moderation_queue_priority'), table_name='moderation_queue')
    op.drop_index(op.f('ix_moderation_queue_is_resolved'), table_name='moderation_queue')
    op.drop_index(op.f('ix_moderation_queue_id'), table_name='moderation_queue')
    op.drop_index(op.f('ix_moderation_queue_flag_type'), table_name='moderation_queue')
    op.drop_table('moderation_queue')
    op.drop_index(op.f('ix_collection_items_id'), table_name='collection_items')
    op.drop_index(op.f('ix_collection_items_collection_id'), table_name='collection_items')
    op.drop_index(op.f('ix_collection_items_bottle_id'), table_name='collection_items')
    op.drop_table('collection_items')
    op.drop_index(op.f('ix_submissions_user_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_status'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_bottle_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_collections_user_id'), table_name='collections')
    op.drop_index(op.f('ix_collections_id'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_bottle_aliases_normalized_alias'), table_name='bottle_aliases')
    op.drop_index(op.f('ix_bottle_aliases_id'), table_name='bottle_aliases')
    op.drop_index(op.f('ix_bottle_aliases_alias'), table_name='bottle_aliases')
    op.drop_table('bottle_aliases')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_display_name'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_bottles_release_year'), table_name='bottles')
    op.drop_index(op.f('ix_bottles_normalized_name'), table_name='bottles')
    op.drop_index(op.f('ix_bottles_name'), table_name='bottles')
    op.drop_index(op.f('ix_bottles_id'), table_name='bottles')
    op.drop_index(op.f('ix_bottles_distillery'), table_name='bottles')
    op.drop_index(op.f('ix_bottles_category'), table_name='bottles')
    op.drop_index(op.f('ix_bottles_brand'), table_name='bottles')
    op.drop_table('bottles')
    # ### end Alembic commands ###
